name: bespoke
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83054
title: Bespoke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#231f20'
    - '#5b595a'
    - '#48efbf'
    - '#08b180'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
