name: null
favicon: null
layout_spectrum: 0.028549017617478967
typography_spectrum: 0.42592338868416846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2893442711792886
  lightness: 0.6478690977673978
  saturation: 0.11704215267673135
  rhythmicContrast: 0.6202024831436574
purpose: []
