name: bespoke
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42592338868416846
title: Bespoke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#231f20'
    - '#5b595a'
    - '#48efbf'
    - '#08b180'
  brandStrength: 0.375
  lightness: 0.6478690977673978
  saturation: 0.11704215267673135
  rhythmicContrast: 0.6202024831436574
purpose: []
